version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: edupolicy-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    build: ./php
    container_name: edupolicy-php
    volumes:
      - ./src:/var/www/html:cached
      - drupal-files:/var/www/html/web/sites/default/files
      - drupal-private:/var/www/html/web/sites/default/private
      - drupal-tmp:/var/www/html/web/sites/default/tmp
    command: >
      sh -c "
        mkdir -p web/sites/default/files web/sites/default/private web/sites/default/tmp &&
        chown -R www-data:www-data web/sites/default/files web/sites/default/private web/sites/default/tmp &&
        php-fpm
      "
    restart: unless-stopped


  db:
    image: mysql:8.0
    container_name: edupolicy-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
  drupal-files:
  drupal-private:
  drupal-tmp:
